TiendaMusical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inicio.urls')),
    path('tienda/',include('tienda.urls')),
    path('registro/',include('autentificacion.urls')),
    path('carro/',include('carro.urls')),
    path('pedidos/',include('pedidos.urls')),
    path('perfil/',include('perfil.urls')),
    path('administradores/',include('administradores.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path

from . import views

app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

tienda/urls.py
from django.urls import path

from .views import tienda , formato

from django.conf import settings

from django.conf.urls.static import static


urlpatterns = [
    path('', tienda, name="Tienda"),
    path('formato/<int:formato_id>/',formato, name="formato"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models



class FormatoDisco(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)
    class Meta:
        verbose_name="FormatoDisco"
        verbose_name_plural="formatoDiscos"

    def __str__(self)  :
        return self.nombre

class Disco(models.Model):
    nombre=models.CharField(max_length=50)
    nombreAlbum=models.CharField(max_length=50)
    artista=models.CharField(max_length=50,null=True)
    precio=models.IntegerField()
    vendidos=models.IntegerField(default=0)
    stock=models.IntegerField(default=1)
    annopublicacion=models.DateField()
    imagen=models.ImageField(upload_to='imgDiscos', null=True,blank=True)
    formatos=models.ForeignKey(FormatoDisco, on_delete=models.CASCADE)
    oferta=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)
    class Meta:
        verbose_name="Disco"
        verbose_name_plural="Discos"

    def __str__(self)  :
        return self.nombre
        

carro/views.py
from django.shortcuts import redirect
from .carro import Carro
from tienda.models import Disco

# Create your views here.
def agregar_producto(request,producto_id):
    carro=Carro(request)
    producto=Disco.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("Tienda")

def eliminar_producto(request,producto_id):
    carro=Carro(request)
    producto=Disco.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("Tienda")

def restar_producto(request,producto_id):
    carro=Carro(request)
    producto=Disco.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("Tienda")

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.http import Http404

from .models import Disco 
from .models import FormatoDisco 



# Create your views here.
def tienda(request):

    all_tipos=FormatoDisco.objects.all()
    all_discos=Disco.objects.all()   
    page= request.GET.get ('page',1)
    try:
        paginator= Paginator (all_discos,10)
        all_discos = paginator.page(page)
    except:
        raise Http404
    data ={
        'entity':all_discos,

        'paginator':paginator,

        "formatos":all_tipos
    }
    
    return render(request,"tienda.html",data)

def formato(request,formato_id):
    

    
    all_tipos=FormatoDisco.objects.all()
    all_formats=FormatoDisco.objects.get(id=formato_id)
    all_discos=Disco.objects.filter(formatos=formato_id)
    page= request.GET.get ('page',1)
    try:
        paginator= Paginator (all_discos,10)
        all_discos = paginator.page(page)
    except:
        raise Http404
    data ={
#        'entity':all_discos,

        'entity':[],
        #'paginator':paginator,

        'paginator':[],
        "formatos":all_tipos
    }
    return render(request,"tienda.html",data)

tienda/templates/carro.html
<table class="table table-bordered" style="color: black;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">Carro Compras</th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-danger">-</a><br>
                        $ {{ value.precio }}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">Sin Productos</div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: ${{ importe_total_carro }}
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div class="input-group mb-3">
                    <input type="text" class="form-control " placeholder="Código promocional" id="codigo_promocional">
                    <div class="input-group-append">
                        <button class="btn btn-secondary"style="margin: 10px;" type="button" id="validar_codigo">Validar</button>
                    </div>
                </div>
            </td>
        </tr>
        {% if request.session.carro.items %}
            <tr>
                <td colspan="3" class="text-center">
                    <a class="btn btn-secondary" href="{% url 'carro:limpiar' %}">Limpiar</a>
                    <a href="{% url 'procesar_pedido' %}" class="btn btn-success">Hacer pedido</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>
</table>

<script>
    document.getElementById('validar_codigo').addEventListener('click', function() {
        var codigo = document.getElementById('codigo_promocional').value;
        if (codigo === 'codigo') {
            alert('Código promocional válido. Se aplicará el descuento por 10%');
        } else {
            alert('Código promocional inválido.');
        }
    });
</script>

tienda/templates/ofertas.html
<div class="container">
   
    <div class="row">
        <h1 class="text-center">Megas Ofertas </h1>

    {% for disco in discos %}
        {% if disco.oferta  %}
        
        <div class="col-md-4">
            <div class="card bg-secondary" style="width: 100%; margin: 5px 5px; height:300px;">
                <div class="card-body" style="text-align: center;">
                    <h5 class="card-title" style="height: 40%;">{{disco.nombre}}</h5>
                    {% if disco.imagen  %}
                    <img src="{{disco.imagen.url}}" width="100" height="100" alt="">
                    {% endif %}
                    <p class="card-text">$&nbsp;{{disco.precio}}</p>
                </div>
            <!--
                <div class="card-footer text-center">
                    <a href="#" class="btn btn-success">Agregar</a>
                </div>
            -->
            </div>
        </div>


        {% endif %}     







    {% endfor %}
    </div>
</div>

tienda/templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

tienda/templates/tienda.html
{% extends "base.html" %}


{% load static %}

{% block titulo %}
Tienda 
{% endblock titulo %}

{% block styles %}
 
<link href="{% static 'tienda/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock styles %}

{% block contenido %}
<div class="container py-3 bg-grey" >
    <div style="float: right; ;">



        {% if request.user.is_authenticated %}

                {% include "carro.html" %}
        {% else %}

            <div class="alert alert-danger text-center " style="margin:5px; ">Iniciar sesion para ver carro</div> 

        {% endif %}

     
    </div>
    <div class="column">

    {% for disco in entity %}

    <div class="col-md-9 "> 
        <div class="d-flex my-5 " style="width: 100%; margin: 5px 5px; height:160px; ">
            <div class="mx-5">
                {% if disco.imagen %}
                <img src="{{disco.imagen.url}}" class="rounded" width="160" height="160" alt="">
                {% endif %}

            </div>

            <div class="column ">
                <h5 class="card-title" >{{disco.nombre}}</h5>
                <div class="d-flex w-100">
                    <div class="w-100" style="min-width:400px;">
                        <p class="card-text">{{disco.artista}}</p>
                        <p class="card-text">$&nbsp;{{disco.precio}}</p>
                    </div>
                    <div class="column">
                        <div>
                            <p class="card-text">Stock:&nbsp; {{disco.stock}}</p>
                            <p class="card-text">Vendidos:&nbsp;{{disco.vendidos}}</p>
                        </div>

                        
                        <div class="card-footer text-end">
                            {% if disco.stock > 0  %}
                            <a href="{% url 'carro:agregar' disco.id %}"  class="btn btn-success mt-2">Agregar</a>
                             {% else %}   
                             <a href="#"  class="btn btn-danger mt-2">OUT</a>
                             {% endif %}

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div> 





    {% endfor %}
    </div>

    <div>
        {% include 'paginator.html' %}
    </div>
</div>
{% endblock %}

  