TiendaMusical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inicio.urls')),
    path('tienda/',include('tienda.urls')),
    path('registro/',include('autentificacion.urls')),
    path('carro/',include('carro.urls')),
    path('pedidos/',include('pedidos.urls')),
    path('perfil/',include('perfil.urls')),
    path('administradores/',include('administradores.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administradores/urls.py
from django.urls import path


from django.conf import settings

from django.conf.urls.static import static

from .views import *

listaLineaPedidos
urlpatterns = [
    path('productos/', productosAdmin, name="productosAdmin"),
    path('Crearproducto/', Crearproducto, name="Crearproducto"),
    path('eliminarProducto/<str:disco_id>/', eliminarProducto, name="eliminarProducto"),
    path('crearDisco/', CrearDisco, name="CrearDisco"),
    path('ListaUsuarios/', ListaUsuarios, name="ListaUsuarios"),
    path('eliminarUsuario/<str:disco_id>/', eliminarUsuario, name="eliminarUsuario"),
    path('editar_producto/<str:disco_id>/', editar_producto, name="editar_producto"),
    path('buscar-discos/', buscar_discos, name='buscar_discos'),
    path('editarUsuario/<str:userss>/', editarUsuario, name="editarUsuario"),
    path('listaPedidos/', listaPedidos, name="listaPedidos"),
    path('listaLineaPedidos/<str:linea_pedido>/', listaLineaPedidos, name="listaLineaPedidos"),

  

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

carro/urls.py
from django.urls import path

from . import views

app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

administradores/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models



class FormatoDisco(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)
    class Meta:
        verbose_name="FormatoDisco"
        verbose_name_plural="formatoDiscos"

    def __str__(self)  :
        return self.nombre

class Disco(models.Model):
    nombre=models.CharField(max_length=50)
    nombreAlbum=models.CharField(max_length=50)
    artista=models.CharField(max_length=50,null=True)
    precio=models.IntegerField()
    vendidos=models.IntegerField(default=0)
    stock=models.IntegerField(default=1)
    annopublicacion=models.DateField()
    imagen=models.ImageField(upload_to='imgDiscos', null=True,blank=True)
    formatos=models.ForeignKey(FormatoDisco, on_delete=models.CASCADE)
    oferta=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)
    class Meta:
        verbose_name="Disco"
        verbose_name_plural="Discos"

    def __str__(self)  :
        return self.nombre
        

administradores/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from tienda.models import Disco,FormatoDisco
from django.contrib.auth.models import User 
from datetime import datetime
from pedidos.models import *
# Create your views here.


## PRODUCTOS
@login_required(login_url='Home')
def buscar_discos(request):
    query = request.GET.get('query')
    discos = Disco.objects.filter(nombre__icontains=query)
    return render(request, 'productos.html', {'discos': discos})

@login_required(login_url='Home')
def productosAdmin(request):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
            all_discos=Disco.objects.all()   
            return render(request,"productos.html",{"discos":all_discos})
            
    return redirect('Home')


@login_required(login_url='Home')
def Crearproducto(request):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
  
            return render(request,"CrearProducto.html")
    return redirect('Home')



@login_required(login_url='Home')
def editar_producto(request, disco_id):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
            if request.method == 'POST':
                noferta = request.POST.get('oferta') 
                noferta = bool(noferta)  
                nnombre=request.POST['nombre']
                nalbum=request.POST['nombreAlbum']
                nartista=request.POST['artista']
                nprecio=request.POST['precio']
                nstock=request.POST['stock']
                nanno=request.POST['annopublicacion']
                nimagen=request.POST.get('imagen')
                nformato=request.POST['formatos']
                nformato=FormatoDisco.objects.get(id=int(nformato))
                now = datetime.now()
            
                Disco.objects.filter(id=disco_id).update(oferta=noferta,nombre=nnombre,nombreAlbum=nalbum,artista=nartista,precio=nprecio,stock=nstock,annopublicacion=nanno,imagen=nimagen,formatos_id=nformato,updated=now)
                return redirect('productosAdmin')
            if  request.method == 'GET':
                disco = Disco.objects.filter(id=disco_id).values().first()
                return render(request,'EditarProducto.html',{"disco":disco})         
    return redirect('Home')



@login_required(login_url='Home')
def eliminarProducto(request,disco_id):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
            disc=Disco.objects.get(id=int(disco_id))
            disc.delete()
            return redirect('productosAdmin')
    return redirect('Home')



def CrearDisco(request):
    if request.method == 'POST':
        for grupo in request.user.groups.all():
            if grupo.name == 'admins':
                nnombre = request.POST['nombre']
                nalbum = request.POST['nombreAlbum']
                nartista = request.POST['artista']
                nprecio = request.POST['precio']
                nstock = request.POST['stock']
                nanno = request.POST['annopublicacion']
                nformato_id = int(request.POST['formatos'])
                noferta = bool(request.POST.get('oferta', False))
                nimagen = request.FILES['imagen']  

                try:
                    formatin = FormatoDisco.objects.get(id=nformato_id)
                except FormatoDisco.DoesNotExist:
                    return redirect('Home')

                dis = Disco(
                    oferta=noferta,
                    nombre=nnombre,
                    nombreAlbum=nalbum,
                    artista=nartista,
                    formatos=formatin,
                    precio=int(nprecio),
                    vendidos=0,
                    stock=int(nstock),
                    annopublicacion=nanno,
                    imagen=nimagen
                )
                dis.save()
                return redirect('productosAdmin')
        return redirect('Home')
    else:
        return redirect('Home')  

## USUARIO 

@login_required(login_url='Home')
def ListaUsuarios (request):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
            lista=User.objects.all()
            return render(request,'listaUsuarios.html',{"users":lista})

    return redirect('Home')

        
@login_required(login_url='Home')
def eliminarUsuario(request,disco_id):

    for grupo in request.user.groups.all(): 
        if grupo.name == 'admins':
            disc=User.objects.get(id=int(disco_id))
            disc.delete()
            return redirect('ListaUsuarios')
    return redirect('Home')

@login_required(login_url='Home')
def editarUsuario(request,userss):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
            if request.method == 'POST':
                mail = request.POST.get('mail') 
                nombre = request.POST.get('nombre')
                User.objects.filter(id=userss).update(username=nombre,email=mail)
 
                return redirect('ListaUsuarios')
            elif request.method == 'GET':
                user = User.objects.filter(id=userss).values().first()
                return render(request, 'editarUsuario.html', {"user": user})         
    return redirect('Home')


#PEDIDOS 
@login_required(login_url='Home')
def listaPedidos(request):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
            lpedido=Pedido.objects.all()
            return render(request,'listaPedidos.html',{"Pedido":lpedido})

    return redirect('Home')

@login_required(login_url='Home')
def listaLineaPedidos(request,linea_pedido):
    for grupo in request.user.groups.all():
        if grupo.name == 'admins':
          
            LineaPedidos=LineaPedido.objects.filter(pedido_id=int(linea_pedido))
            
            return render(request,'LineaPedidos.html',{"LPedido":LineaPedidos,"linea_pedido":int(linea_pedido)})

    return redirect('Home')

administradores/templates/CrearProducto.html
{% extends "base.html" %}


{% load static %}

{% block titulo %}
Tienda 
{% endblock titulo %}


{% block styles %}

<link href="{% static 'administradores/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock styles %}

{% block contenido %}

<div id="content" >
        <h1>Añadir Disco</h1>
        <div id="content-main">
            <form action="/administradores/crearDisco/" method="post" enctype="multipart/form-data"  id="disco_form" novalidate=""><input type="hidden" name="csrfmiddlewaretoken" value="9eUvHrVCp3bBqLOy7V7AGlZuyuJ0mg7TSrZesIZ96Bda5INx7C2w6UUgqyBBCARl">{% csrf_token %}
                <div class="my-2">
                    <fieldset class="module aligned  ">
                        <div class="form-row field-nombre my-2">
                            <div>
                                <div class="flex-container">
                                    <label class="required" for="id_nombre">Nombre:</label>
                                    <input type="text" name="nombre" class="vTextField" maxlength="50" required="" id="id_nombre">
                                    <span id="nombreError" class="error-message"></span>
                                </div>
                                  
                            </div>
                        </div>
                        <div class="form-row field-nombreAlbum my-2">
                            <div>
                                <div class="flex-container"> 
                                    <label class="required" for="id_nombreAlbum">NombreAlbum:
                                    </label> 
                                    <input type="text" name="nombreAlbum" class="vTextField" maxlength="50" required="" id="id_nombreAlbum">
                                    <span id="albumError" class="error-message"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-artista my-2">
                            <div>
                                <div class="flex-container"> 
                                    <label class="required" for="id_artista">Artista:
                                    </label> 
                                    <input type="text" name="artista" class="vTextField" maxlength="50" required="" id="id_artista"> 
                                    <span id="artistaError" class="error-message"></span>

                                </div>
                            </div>
                        </div>
                        <div class="form-row field-precio my-2">
                            <div>
                                <div class="flex-container"> 
                                        <label class="required" for="id_precio">Precio:</label>
                                        <input type="text" name="precio" class="vIntegerField" required id="id_precio">
                                        <span id="precioError" class="error-message"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-vendidos my-2">
                            <div>
                                <div class="flex-container"> 
                                    <label class="required" for="id_vendidos">Vendidos:</label> 
                                    <input type="text" name="vendidos" value="0" class="vIntegerField" required="" id="id_vendidos"> 
                                    <span id="vendidosError" class="error-message"></span>

                                </div>
                            </div>
                        </div>
                        <div class="form-row field-stock my-2">
                            <div>
                                <div class="flex-container"> 
                                    <label class="required" for="id_stock">Stock:</label> 
                                    <input type="text" name="stock" value="1" class="vIntegerField" required="" id="id_stock"> 
                                    <span id="stockError" class="error-message"></span>

                                </div>
                            </div>
                        </div>
                        <div class="form-row field-annopublicacion my-2">
                            <div class="row form-group">
                                <div class="d-flex col-sm-4 h-75  align-items-end">
                                    <label class="mr-2">Año Publicacion:&nbsp;&nbsp;</label>
                                    <input name="annopublicacion" type="date" name="txtapa" id="id_annopublicacion"  class=" form-control form-control-lg" />
                                    <a class=" pb-3" href="#" onclick="setTodayDate();">&nbsp;&nbsp;Hoy&nbsp;&nbsp;</a>
                                  
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-imagen my-2">
                            <div>
                                <div class="flex-container"> <label for="id_imagen">Imagen:</label> <input type="file" name="imagen" accept="image/*" id="id_imagen"> </div>
                            </div>
                        </div>
                        <div class="form-row field-formatos my-2">
                            <div>
                                <div class="flex-container"> <label class="required" for="id_formatos">Formatos:</label>
                                    <div class="related-widget-wrapper" data-model-ref="FormatoDisco"> <select name="formatos" required="" id="id_formatos">
                                                        <option value="0" selected="">---------</option>
                                                        
                                                        <option value="1">Cassette</option>
                                                        
                                                        <option value="2">CD</option>
                                                        
                                                        <option value="3">Vinillos usados</option>
                                                        
                                                        <option value="4">Vinillos</option>
                                                        
                                                        </select>
                                                        <span id="formatoError" class="error-message"></span>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-oferta my-2">
                            <div>
                                <div class="flex-container checkbox-row"> 
                                    <input type="checkbox" name="oferta" id="id_oferta" checked="">
                                    <label class="vCheckboxLabel" for="id_oferta">Oferta</label>
                                 </div>
                            </div>
                        </div>
                        <div class="form-row field-created my-2">
                            <div>
                                <div class="flex-container"> <label>Created:</label>
                                    <div class="readonly">-</div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row field-updated my-2">
                            <div>
                                <div class="flex-container"> <label>Updated:</label>
                                    <div class="readonly">-</div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <div class="submit-row my-2"> 
                        <a href="{% url 'productosAdmin' %}" class="btn btn-danger">Cancelar</a>
                        <button  type="submit" value="Guardar" class="default btn btn-success" >Guardar</button>
                        
                    </div>
                  
                </div>
            </form>
        </div>
     </div>


{% endblock %}
{% block js %}



<script src="{% static 'administradores/js/main.js' %}" ></script>



{% endblock js %}

administradores/templates/EditarProducto.html
{% extends "base.html" %}


{% load static %}

{% block titulo %}
Editando a {{ disco.nombre }}
{% endblock titulo %}

{% block styles %}

<link href="{% static 'administradores/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock styles %}

{% block contenido %}


<div id="content-main " class="my-3">
    <form action="/administradores/editar_producto/{{  disco.id }}/"  enctype="multipart/form-data" method="POST" id="disco_form" novalidate=""><input type="hidden"
            name="csrfmiddlewaretoken" value="M0OwozZdXWdyamLniCwQnCguKZL08TkuaDvulrSQyWGsfe91DnID8pMlIGFUCdlF">
            {% csrf_token %}
        <div>
            <fieldset class="module aligned ">
                <div class="form-row field-nombre mt-3">
                    <div>
                        <div class="flex-container">
                            <label class="required" for="id_nombre">Nombre:</label>
                            <input type="text" name="nombre" value="{{ disco.nombre }}" class="vTextField"
                                maxlength="50" required="" id="id_nombre">

                        </div>

                    </div>


                </div>

                <div class="form-row field-nombreAlbum my-2">


                    <div>

                        <div class="flex-container">

                            <label class="required" for="id_nombreAlbum">NombreAlbum:</label>

                            <input type="text" name="nombreAlbum" value="{{ disco.nombreAlbum }}" class="vTextField"
                                maxlength="50" required="" id="id_nombreAlbum">


                        </div>

                    </div>


                </div>

                <div class="form-row field-artista my-2">


                    <div>

                        <div class="flex-container">

                            <label class="required" for="id_artista">Artista:</label>

                            <input type="text" name="artista" value="{{ disco.artista }}" class="vTextField"
                                maxlength="50" required="" id="id_artista">


                        </div>

                    </div>


                </div>

                <div class="form-row field-precio my-2">


                    <div>

                        <div class="flex-container">

                            <label class="required" for="id_precio">Precio:</label>

                            <input type="number" name="precio" value="{{ disco.precio }}" class="vIntegerField"
                                required="" id="id_precio">


                        </div>

                    </div>


                </div>

                <div class="form-row field-vendidos my-2">


                    <div>

                        <div class="flex-container">

                            <label class="required" for="id_vendidos">Vendidos:</label>

                            <input type="number" name="vendidos" value="{{ disco.vendidos }}" class="vIntegerField"
                                required="" id="id_vendidos">


                        </div>

                    </div>


                </div>

                <div class="form-row field-stock my-2">


                    <div>

                        <div class="flex-container">

                            <label class="required" for="id_stock">Stock:</label>

                            <input type="number" name="stock" value="{{ disco.stock }}" class="vIntegerField"
                                required="" id="id_stock">


                        </div>

                    </div>


                </div>

                <div class="form-row field-annopublicacion my-2">
                        <div class="row form-group">
                            <div class="d-flex col-sm-4 h-75  align-items-end">
                                <label class="mr-2">Año Publicacion:&nbsp;&nbsp;</label>
                                <input name="annopublicacion" type="date" name="txtapa" id="id_annopublicacion" value="{{ disco.annopublicacion|date:'Y-m-d' }}" class=" form-control form-control-lg" />
                                <a href="#"onclick="setTodayDate();">&nbsp;&nbsp;Hoy&nbsp;&nbsp;</a>
                              
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row field-imagen my-2">


                    <div>

                        <div class="flex-container">

                            <label for="id_imagen">Imagen:</label>

                            <p class="file-upload">Actualmente: <a href="{{ disco.imagen }}">1</a>
                                <span class="clearable-file-input">
                                    <input type="checkbox" name="imagen-clear" id="imagen-clear_id">
                                    <label for="imagen-clear_id">Limpiar</label></span><br>
                                Modificar:
                                <input type="file" name="imagen" accept="image/*" id="id_imagen">
                            </p>


                        </div>

                    </div>


                </div>

                <div class="form-row field-formatos my-2">


                    <div>

                        <div class="flex-container">

                            <label class="required" for="id_formatos">Formatos:</label>

                            <div class="related-widget-wrapper" data-model-ref="FormatoDisco">
                                <select name="formatos" required="" id="id_formatos">
                                    <option value="">---------</option>
                                    {% if disco.formatos_id == 1 %}
                                    <option value="1" selected="">CD</option>
                                    <option value="2">Cassette</option>
                                    <option value="3">Vinillos</option>
                                    <option value="4">Vinillos usados</option>

                                    {% endif %}
                                    {% if disco.formatos_id == 2 %}
                                    <option value="1">CD</option>
                                    <option value="2" selected="">Cassette</option>
                                    <option value="3">Vinillos</option>
                                    <option value="4">Vinillos usados</option>

                                    {% endif %}
                                    {% if disco.formatos_id == 3 %}
                                    <option value="1">CD</option>
                                    <option value="2">Cassette</option>
                                    <option value="3" selected="">Vinillos</option>
                                    <option value="4">Vinillos usados</option>
                                    {% endif %}
                                    {% if disco.formatos_id == 4 %}
                                    <option value="1">CD</option>
                                    <option value="2">Cassette</option>
                                    <option value="3">Vinillos</option>
                                    <option value="4" selected="">Vinillos usados</option>
                                    {% endif %}

                                </select>



                            </div>


                        </div>

                    </div>


                </div>

                <div class="form-row field-oferta my-2">

                    <div>
                        <div class="flex-container checkbox-row">
                            {% if disco.oferta %}
                            <input type="checkbox" name="oferta" id="id_oferta" checked>
                            <label class="vCheckboxLabel" for="id_oferta">Oferta</label>
                            {% else %}
                            <input type="checkbox" name="oferta" id="id_oferta">
                            <label class="vCheckboxLabel" for="id_oferta">Oferta</label>
                            {% endif %}

                        </div>

                    </div>


                </div>

                <div class="form-row field-created my-2">


                    <div>

                        <div class="flex-container">

                            <label>Created:</label>

                            <div class="readonly">{{ disco.created|date:"Y-m-d" }}</div>


                        </div>

                    </div>

                </div>

                <div class="form-row field-updated my-2">
                    <div>
                        <div class="flex-container">

                            <label>Updated:</label>

                            <div class="readonly">{{ disco.updated|date:"Y-m-d" }}</div>

                        </div>

                    </div>


                </div>

            </fieldset>
            <div class="submit-row">

             

                <a href="{% url 'productosAdmin' %}" class="btn btn-danger">Cancelar</a>
                <input type="submit" value="Guardar" class="default btn btn-success" name="_save">
            </div>
        </div>
    </form>
</div>

{% endblock %}

{% block js %}


<script src="{% static 'administradores/js/main.js' %}" ></script>




{% endblock js %}

administradores/templates/EditarUsuario.html
{% extends "base.html" %}


{% load static %}

{% block titulo %}
Editar Usuario {{  user.username }}
{% endblock titulo %}

{% block styles %}

<link href="{% static 'administradores/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock styles %}

{% block contenido %}


<div id="content-main " class="my-3">
    <h1>Editar Usuario</h1>
    <form action="/administradores/editarUsuario/{{  user.id }}/"  enctype="multipart/form-data" method="POST" id="disco_form" novalidate="">
        {% csrf_token %}
            <div class="form-row field-nombre my-2">
                <div>
                    <div class="flex-container"> 
                        <label class="" >ID usuario:</label> 
                        <label class="" >{{  user.id }}</label>  
                    </div>
                </div>
            </div>
            <div class="form-row field-nombre my-2">
                <div>
                    <div class="flex-container"> 
                        <label class="required" for="id_nombre_user">Nombre:
                        </label> 
                        <input type="text" name="nombreUser" class="vTextField" value="{{ user.username }}" maxlength="50" required="" id="id_nombre_user"> 
                        <span id="nombreUserError" class="error-message"></span>

                    </div>
                </div>
            </div>

            <div class="form-row field-mail my-2">
                <div>
                    <div class="flex-container"> 
                        <label class="required" for="id_mail">Email:
                        </label> 
                        <input type="text" name="mail" class="vTextField"value="{{ user.email }}" maxlength="50" required="" id="id_mail"> 
                        <span id="mailError" class="error-message"></span>

                    </div>
                </div>
            </div>

            <div class="submit-row my-2"> 
                <a href="{% url 'productosAdmin' %}" class="btn btn-danger">Cancelar</a>
                <button  type="submit" value="Guardar" class="default btn btn-success" >Guardar</button>
                
            </div>

    </form>
</div>

{% endblock %}

{% block js %}


<script src="{% static 'administradores/js/main.js' %}" ></script>




{% endblock js %}

administradores/templates/LineaPedidos.html
{% extends "base.html" %}


{% load static %}

{% block titulo %}
Pedido  {{ linea_pedido }}
{% endblock titulo %}

{% block styles %}
 
<link href="{% static 'administradores/css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock styles %}

{% block contenido %}
<div class="container">
    <div class="row">
        
        <h1>N° DE PEDIDO {{ linea_pedido }}</h1>
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Usuario</th>
                    <th>Producto</th>
                    <th>cantidad</th>
                    <th>created_at</th>
                </tr>
            </thead>

            {% for pedido in LPedido %}
            <tbody>
                <tr>    
                    <td>{{ pedido.id }}</td>
                    <td>{{ pedido.user }}</td>
                    <td>{{ pedido.producto }}</td>
                    <td>{{ pedido.cantidad }}</td>
                    <td>{{ pedido.created_at }}</td>
                    
                   
                </tr>
            </tbody>
            {% endfor %}

        </table>
    </div>
</div>

{% endblock %}

{% block js %}


{% endblock js %}